env:
  MAGE_VERSION: v1.15.0

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Install Mage
      uses: magefile/mage-action@a662bd8c29d8106879588cfff83b2faf6e6f59db # v4.0.0
      with:
        version: ${{ env.MAGE_VERSION }}
        install-only: true
