env:
  GO_VERSION: "1.24"
  MAGE_VERSION: v1.15.0

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Mage
      uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
      with:
        version: ${{ env.MAGE_VERSION }}
        install-only: true
