env:
  GO_VERSION: "1.24"
  MAGE_VERSION: v1.15.0

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install Mage
      uses: magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b # v3.1.0
      with:
        version: ${{ env.MAGE_VERSION }}
        install-only: true
