---
kind: pipeline
type: docker
name: publish

steps:
  - name: github-release
    image: golang:1.20.6-alpine3.18
    environment:
      GITHUB_APP_ID:
        from_secret: gh-app-id
      GITHUB_APP_INSTALLATION_ID:
        from_secret: gh-app-installation-id
      GITHUB_APP_PRIVATE_KEY:
        from_secret: gh-app-private-key
    commands:
      - apk add git

      - cd /tmp
      - git clone https://github.com/magefile/mage
      - cd mage
      - go run bootstrap.go

      - cd /drone/src
      - mage gitHub:release $DRONE_TAG

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  ref:
    - refs/tags/v*

---
name: gh-app-private-key
kind: secret
get:
  name: private-key
  path: infra/data/ci/detect-angular-dashboards/github-app
---
name: gh-app-installation-id
kind: secret
get:
  name: app-installation-id
  path: infra/data/ci/detect-angular-dashboards/github-app
---
name: gh-app-id
kind: secret
get:
  name: app-id
  path: infra/data/ci/detect-angular-dashboards/github-app

---
kind: signature
hmac: 1f26ddf5fad75f1f289e226b3d25d7991d914e83a305fd42c287aafda8c90ab1

...
